### ISSUE TITLE
Crash on KakaoLogin - profilePicture must not be null

### ISSUE THREAD

**Issue by WindSekirun** [WindSekirun/RxSocialLogin#35]
```
Fatal Exception: java.lang.IllegalStateException: profilePicture must not be null
       at com.github.windsekirun.rxsociallogin.kakao.KakaoLogin$requestMe$1.onSuccess(KakaoLogin.kt:124)
       at com.github.windsekirun.rxsociallogin.kakao.KakaoLogin$requestMe$1.onSuccess(KakaoLogin.kt:84)
       at com.kakao.network.callback.ResponseCallback.onSuccessForUiThread(ResponseCallback.java:76)
       at com.kakao.network.tasks.KakaoResultTask$1$1.run(KakaoResultTask.java:78)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by WindSekirun** [comment]
released as 1.1.2
